# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # job 1
  test-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
          cache: true
        id: go

      # - name: Get dependencies
      #   run: |
      #     go get -v -t -d ./...

      # - name: Lint
      #   run: |
      #     go vet -stdmethods=false $(go list ./...)

      #     go mod tidy
      #     if ! test -z "$(git status --porcelain)"; then
      #       echo "Please run 'go mod tidy'"
      #       exit 1
      #     fi

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3

  test-win:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
          cache: true

      - name: Test
        run: |
          go mod verify
          go mod download
          go test ./...